import assert from "node:assert/strict";
import test from "node:test";
import { RateLimitError, createApiKey, hashApiKey, isAdminEmail, normalizeDailyLimit, parseBearer, rateLimitHeaders } from "../server/index.js";
test("creates and parses product bearer keys",()=>{const token=createApiKey("bay_sk_");assert.equal(parseBearer(`Bearer ${token}`,"bay_sk_"),token);assert.equal(hashApiKey(token).length,64);assert.equal(parseBearer(`Bearer ${token}`,"other_sk_"),null)});
test("normalizes finite limits",()=>{assert.equal(normalizeDailyLimit("250"),250);assert.equal(normalizeDailyLimit("0"),100)});
test("administrators are explicitly unlimited",()=>{assert.equal(isAdminEmail("ADMIN@example.com","admin@example.com"),true);assert.deepEqual(rateLimitHeaders({admin:true,limit:1,remaining:0,windowStart:"2026-08-08"}),{"x-ratelimit-limit":"unlimited","x-ratelimit-remaining":"unlimited"})});
test("finite users receive standard quota metadata",()=>{assert.deepEqual(rateLimitHeaders({limit:10,remaining:4,windowStart:"2026-08-08"}),{"x-ratelimit-limit":"10","x-ratelimit-remaining":"4","x-ratelimit-reset":"1786233600"})});
test("weighted quota metadata is emitted without unsafe header newlines",()=>{assert.deepEqual(rateLimitHeaders({limit:1000,remaining:875,windowStart:"2026-08-08",cost:25,requestId:"req_123",retryAfter:30,warning:"Low\r\nquota",tier:"claimed"}),{"x-ratelimit-limit":"1000","x-ratelimit-remaining":"875","x-ratelimit-reset":"1786233600","x-ratelimit-cost":"25","x-request-id":"req_123","retry-after":"30","x-ratelimit-warning":"Low quota","x-ratelimit-tier":"claimed"})});
test("rate limit errors retain their structured fair-use alternatives",()=>{const headers=rateLimitHeaders({limit:1000,remaining:20,windowStart:"2026-08-08",cost:40,requestId:"req_429"});const error=new RateLimitError(headers,{error:"This request needs 40 units",scope:"daily",cost:40,remaining:20,shortfall:20,retryAt:"2026-08-09T00:00:00Z",alternatives:[{kind:"reduce_limit",label:"Return 25 rows",cost:10}]});assert.equal(error.status,429);assert.equal(error.body.code,"quota_exceeded");assert.equal(error.body.alternatives[0].cost,10);assert.equal(error.fair_use.alternatives[0].label,"Return 25 rows");assert.equal(error.headers["x-request-id"],"req_429")});
